name = "chillaula"

workers_dev = true
main = "./build/index.js"
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2023-10-30"

[site]
  bucket = "./public"

[build]
  command = "npm run build"
